### ISSUE TITLE
cpu好像不能变频

### ISSUE THREAD

**Issue by wkgr2009** [wmyfelix/X10DAi-hackintosh#1]
作者应该是中国人把
我的同款e52683*2双路ch20跑分比win系统低。

**Comment by mingww64** [comment]
用cpufriendfriend自行调频

**Comment by mingww64** [comment]
> 作者应该是中国人把
> 我的同款e52683*2双路ch20跑分比win系统低。

v2以下用ssdtprgen

**Comment by wkgr2009** [comment]
我的是e5 2683v3 主板也是超微x10dai，你的可以变频吗？我其实就显卡是gt740其它和你的一样

**Comment by mingww64** [comment]
> 我的是e5 2683v3 主板也是超微x10dai，你的可以变频吗？我其实就显卡是gt740其它和你的一样

可不可以变频我不清楚，geekbench5跑分比windows10高，应该是正常的。
我是用cpufriendfriend生成的cpufrienddataprovider.kext，LFM始终设置不了，无法睡眠。你的可以睡眠吗

**Comment by wkgr2009** [comment]
大佬，您新的efi好像有点问题，efi/oc/deivers里面少了一个OpenCanopy.efi文件，少了这个文件启动不了。问一下大佬，你这里提供的bios文件是不是把wake on lan 给修改没了，我在bios里面找不到网络唤醒相关选项。

**Comment by mingww64** [comment]
> 大佬，您新的efi好像有点问题，efi/oc/deivers里面少了一个OpenCanopy.efi文件，少了这个文件启动不了。问一下大佬，你这里提供的bios文件是不是把wake on lan 给修改没了，我在bios里面找不到网络唤醒相关选项。

嘻嘻，不是大佬。
不会用git，已经重新推送了，现在是完整的，请生成自己的序列号。
刚看了bios，是有这个功能的，之前还不知道。需要在pcie设置里将Onboard LAN Option ROM Type 改为［EFI］，然后返回Advanced就会显示网卡（也许需要重启）
对了，您的能睡眠吗

**Comment by wkgr2009** [comment]
> > 大佬，您新的efi好像有点问题，efi / oc / deivers里面少了一个OpenCanopy.efi文件，少了这个文件启动不了。问一下大佬，你这里提供的bios文件是不是把wake on lan给修改没了，我在bios里面找到网络唤醒相关选项。
> 
> 嘻嘻，不是大佬。
> 不会用git，已经重新按下了，现在是完整的，请生成自己的序列号。
> 刚看了bios，是有这个功能的，之前还不知道。需要在pcie设置里将Onboard LAN Option ROM类型转换为[EFI]，然后返回Advanced就会显示网卡（也许需要重启）
> 对了，您的能睡眠吗
我没怎么玩，所以不知道，过几天用的时候测试一下。

**Comment by wkgr2009** [comment]
> > > 大佬，您新的efi好像有点问题，efi / oc / deivers里面少了一个OpenCanopy.efi文件，少了这个文件启动不了。问一下大佬，你这里提供的bios文件是不是把修改没了，我在bios里面找到网络唤醒相关选项。
> > 
> > 
> > 嘻嘻，不是大佬。
> > 不会用git，已经重新点击了，现在是完整的，请生成自己的序列号。
> > 刚看了bios，是有这个功能的，之前还不知道。需要在pcie设置里将Onboard LAN Option ROM类型转换为[EFI]，然后返回Advanced就会显示网卡（也许需要重启）
> > 对了，您的能睡眠吗
> > 我没怎么玩，所以不知道，过几次用的时候测试一下。

这几天玩了一下，发现屏幕可以熄灭但睡眠无法启用，可能和usb接口没有定制有关，另外你的efi里面没有放usb3.0的驱动，所以usb3.0没有启用。不过我的黑苹果莫名其妙的卡顿，不知为何，刚开始我以为是我的机械硬盘问题，后来换了固态发现依旧如此，我用的是sata接口的固态。

**Comment by mingww64** [comment]
> > > > 大佬，您新的efi好像有点问题，efi / oc / deivers里面少了一个OpenCanopy.efi文件，少了这个文件启动不了。问一下大佬，你这里提供的bios文件是不是把修改没了，我在bios里面找到网络唤醒相关选项。
> > > 
> > > 
> > > 嘻嘻，不是大佬。
> > > 不会用git，已经重新点击了，现在是完整的，请生成自己的序列号。
> > > 刚看了bios，是有这个功能的，之前还不知道。需要在pcie设置里将Onboard LAN Option ROM类型转换为[EFI]，然后返回Advanced就会显示网卡（也许需要重启）
> > > 对了，您的能睡眠吗
> > > 我没怎么玩，所以不知道，过几次用的时候测试一下。
> 
> 这几天玩了一下，发现屏幕可以熄灭但睡眠无法启用，可能和usb接口没有定制有关，另外你的efi里面没有放usb3.0的驱动，所以usb3.0没有启用。不过我的黑苹果莫名其妙的卡顿，不知为何，刚开始我以为是我的机械硬盘问题，后来换了固态发现依旧如此，我用的是sata接口的固态。

刚刚把主板卖了。
bios设置
ehci 、xhci hand off 打开 
usb3.0设为enabled非auto。

关于卡顿可尝试:
cpufrienddataprovider.kext删除，用cpufriendfriend重新生成。
请查看log

**Comment by zenbarski** [comment]
首先感謝你，x10dai 這版，cfg lock解鎖，這幾年真沒看到誰做出來，小弟還是有問題請教進入bios我直接f3最佳化然後才改，bios除了南僑usb設置之外，還有沒有需要注意的，我只把pcie裏leagy設為uefi，4gdecoding slot1 yes，cpu電源管理社custom c0/c1<還有沒有其他地方要特別開關的（你的efi我卡在一對日期與網址沒法進入recovery），要順利安裝，我都是拆掉一顆cpu安裝完成再裝上，系統非常容易崩潰，請大佬開示

**Comment by mingww64** [comment]
> 首先感謝你，x10dai 這版，cfg lock解鎖，這幾年真沒看到誰做出來，小弟還是有問題請教進入bios我直接f3最佳化然後才改，bios除了南僑usb設置之外，還有沒有需要注意的，我只把pcie裏leagy設為uefi，4gdecoding slot1 yes，cpu電源管理社custom c0/c1<還有沒有其他地方要特別開關的（你的efi我卡在一對日期與網址沒法進入recovery），要順利安裝，我都是拆掉一顆cpu安裝完成再裝上，系統非常容易崩潰，請大佬開示

4g decoding 直接Enabled就好，不需要exclude slot 1
电源管理我都是默认的power efficient不用设为custom
config文件仅适用于e5 v3系列，不知道你的是不是v4。
关于拆掉一颗cpu才能安装我没遇到过，kext里有applemcereporterdisabler.kext应该能解决这个问题啊
主板我前几天卖了，也没办法测试。可以把开机卡verbose拍下来发一下
也许可以尝试关闭bios里的x2-apic

**Comment by zenbarski** [comment]
感謝回覆，我的cpu是e5-2666v3x2顯卡rx580 8g（在你的EFI/DeviceproPerties/我刪除了所有設置，保留alcid=1)，除了原有EFI有關Ｄevice顯卡設置外,其他都沒做更動，有點不明白，bios裡的x2-apci這是？還有我在你發的bios去了微碼
![IMG_3226](https://user-images.githubusercontent.com/31694766/116670925-e7ac7f00-a9d2-11eb-8afa-4378f66d249c.JPG)
![IMG_3227](https://user-images.githubusercontent.com/31694766/116670930-ea0ed900-a9d2-11eb-941a-1dbd3930a20a.JPG)
![IMG_3228](https://user-images.githubusercontent.com/31694766/116670935-ebd89c80-a9d2-11eb-97a5-0ca24962e01e.JPG)

**Comment by zenbarski** [comment]
找到了x2 apci 是關閉的

**Comment by mingww64** [comment]
> 感謝回覆，我的cpu是e5-2666v3x2顯卡rx580 8g（在你的EFI/DeviceproPerties/我刪除了所有設置，保留alcid=1)，除了原有EFI有關Ｄevice顯卡設置外,其他都沒做更動，有點不明白，bios裡的x2-apci這是？還有我在你發的bios去了微碼
> ![IMG_3226](https://user-images.githubusercontent.com/31694766/116670925-e7ac7f00-a9d2-11eb-8afa-4378f66d249c.JPG)
> ![IMG_3227](https://user-images.githubusercontent.com/31694766/116670930-ea0ed900-a9d2-11eb-941a-1dbd3930a20a.JPG)
> ![IMG_3228](https://user-images.githubusercontent.com/31694766/116670935-ebd89c80-a9d2-11eb-97a5-0ca24962e01e.JPG)

我也不清楚了，确定用的原版镜像吗，清除过nvram吗

**Comment by zenbarski** [comment]
沒事，還是感謝你，我把bios改回你原始發出來的再試試看，謝謝

**Comment by mingww64** [comment]
> 感謝回覆，我的cpu是e5-2666v3x2顯卡rx580 8g（在你的EFI/DeviceproPerties/我刪除了所有設置，保留alcid=1)，除了原有EFI有關Ｄevice顯卡設置外,其他都沒做更動，有點不明白，bios裡的x2-apci這是？還有我在你發的bios去了微碼
> ![IMG_3226](https://user-images.githubusercontent.com/31694766/116670925-e7ac7f00-a9d2-11eb-8afa-4378f66d249c.JPG)
> ![IMG_3227](https://user-images.githubusercontent.com/31694766/116670930-ea0ed900-a9d2-11eb-941a-1dbd3930a20a.JPG)
> ![IMG_3228](https://user-images.githubusercontent.com/31694766/116670935-ebd89c80-a9d2-11eb-97a5-0ca24962e01e.JPG)

尝试仅用原有config增加smbios后引导macos，bios不作更改。
如果在我的配置下依然无法开机那我也无能为力

**Comment by zenbarski** [comment]
好的，按照你說的，若有新的結果再向你說明，感謝，我先試試看

**Comment by zenbarski** [comment]
你判斷問題很準確、初步問題就是processortype（自定義cpu型號）我習慣性把它設為0造成問題，但我安裝時碰到，載入更新失敗，請問安裝時需要聯網？
![IMG_3229](https://user-images.githubusercontent.com/31694766/116677351-b172fd80-a9da-11eb-9dcb-2ac0a66d70d8.JPG)

**Comment by mingww64** [comment]
> 你判斷問題很準確、初步問題就是processortype（自定義cpu型號）我習慣性把它設為0造成問題，但我安裝時碰到，載入更新失敗，請問安裝時需要聯網？
> ![IMG_3229](https://user-images.githubusercontent.com/31694766/116677351-b172fd80-a9da-11eb-9dcb-2ac0a66d70d8.JPG)

不知道为何不能直接邮箱回复
![Screenshot_2021-05-02-07-42-07-736_com android email](https://user-images.githubusercontent.com/58871134/116797601-f2bdf700-ab19-11eb-8602-d5d88d29630c.jpg)

**Comment by zenbarski** [comment]
感謝

**Comment by Lasx** [comment]
> i這是？還有我在你發的

删除微码的bios能不能共享一个？

**Comment by mingww64** [comment]
> > i這是？還有我在你發的
> 
> 删除微码的bios能不能共享一个？

没有。

**Comment by Lasx** [comment]
> > > i這是？還有我在你發的
> > 
> > 
> > 删除微码的bios能不能共享一个？
> 
> 没有。

还是想打个鸡血

**Comment by mingww64** [comment]
> > > > i這是？還有我在你發的
> > > 
> > > 
> > > 删除微码的bios能不能共享一个？
> > 
> > 
> > 没有。
> 
> 还是想打个鸡血

自己做，欢迎pr。我目前没有这个机器。
